export const settings = {
	adBlock: "adBlock",
	advanced: {
		root: "advanced",
		qobuzUrl: "advanced.qobuzUrl",
	},
	api: "api",
	apiSettings: {
		root: "apiSettings",
		port: "apiSettings.port",
		hostname: "apiSettings.hostname",
	},
	disableBackgroundThrottle: "disableBackgroundThrottle",
	disableHardwareMediaKeys: "disableHardwareMediaKeys",
	enableDiscord: "enableDiscord",
	discord: {
		detailsPrefix: "discord.detailsPrefix",
		buttonText: "discord.buttonText",
		includeTimestamps: "discord.includeTimestamps",
		showSong: "discord.showSong",
		showIdle: "discord.showIdle",
		idleText: "discord.idleText",
		usingText: "discord.usingText",
	},
	ListenBrainz: {
		root: "ListenBrainz",
		enabled: "ListenBrainz.enabled",
		api: "ListenBrainz.api",
		token: "ListenBrainz.token",
		delay: "ListenBrainz.delay",
	},
	flags: {
		root: "flags",
		disableHardwareMediaKeys: "flags.disableHardwareMediaKeys",
		gpuRasterization: "flags.gpuRasterization",
		enableWaylandSupport: "flags.enableWaylandSupport",
	},
	menuBar: "menuBar",
	minimizeOnClose: "minimizeOnClose",
	mpris: "mpris",
	notifications: "notifications",
	playBackControl: "playBackControl",
	singleInstance: "singleInstance",
	skipArtists: "skipArtists",
	skippedArtists: "skippedArtists",
	staticWindowTitle: "staticWindowTitle",
	trayIcon: "trayIcon",
	updateFrequency: "updateFrequency",
	windowBounds: {
		root: "windowBounds",
		width: "windowBounds.width",
		height: "windowBounds.height",
	},
};
